### ISSUE TITLE
WARNING: Error loading config file: .dockercfg: $HOME is not defined

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode_Installer#116]
During dappnode installation at the step of [**Loading DAppNode Core...**](https://github.com/dappnode/DAppNode_Installer/blob/48dd5c81264b331e5b1f1e65c5c2f7ef6c1315b6/build/dappnode/scripts/dappnode_install.sh#L283), it is throw several warmings for each docker image loaded:
```WARNING: Error loading config file: .dockercfg: $HOME is not defined```

This is not very useful friendly and users may think things went wrong during installation
Should be resarch if this has any impact, apparently it does not

**Source of the problem**: may be related to https://github.com/docker/cli/pull/2934

**Possible solution**: according to the possible source of the problem, the issue could be solved by updating the docker version to a docker version newer than the PR merged that solved this issue: https://github.com/docker/cli/releases

![image](https://user-images.githubusercontent.com/41727368/116441330-a6409600-a851-11eb-83e6-d2816e696aac.png)

**Comment by dapplion** [comment]
Oh right good point! What if we set the $HOME variable too? What is it expected value?

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DAppNode_Installer/pull/122
