### ISSUE TITLE
Show access credentials

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode_Installer#127]
To improve the User experience with dappnode, there should be shown credentials to the user to access to DAppNode. Based on the current priority in dappnode, there should be shown in the following order depending if such service is working or not

1. WIFI
2. AVAHI
3. VPN: Wireguard > open VPN

- [x] Find ways to determine for each service if is working or not
- [x] Show credentials/endpoints for working service based on priority

**Comment by dapplion** [comment]
Maybe we can start refering to Avahi as .local network access which is more understandable

**Comment by pablomendezroyo** [comment]
> Maybe we can start refering to Avahi as ".local network access" which is more understandable

Sounds good, but I think is too long to show in a UI

**Comment by dapplion** [comment]
> > Maybe we can start refering to Avahi as ".local network access" which is more understandable
> 
> Sounds good, but I think is too long to be show in a UI

Hmm, what could be a better name? ".local UI",
