### ISSUE TITLE
Improve repository filestructure

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode_Installer#128]
Edit the current file structure of the repository to make things clear

**Comment by dapplion** [comment]
The scripts are referenced from the dappnode/DAppNode repo, so we can safely change the fs structure :+1: 
- https://prerequisites.dappnode.io -> https://github.com/dappnode/DAppNode/releases/download/v0.2.44/dappnode_install_pre.sh
- https://installer.dappnode.io -> https://github.com/dappnode/DAppNode/releases/download/v0.2.44/dappnode_install.sh

**Comment by dapplion** [comment]
It would be awesome to document in the main README the different "entrypoint" scripts, how and where they are used. Also what's the purpose of the .dappnode_profile and any other non-trivial items
