### ISSUE TITLE
Change way Wireguard is presented to the users

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DAppNode_Installer#146]
Use Wireguards API to serve configuration files to users and after https://github.com/dappnode/DNP_WIREGUARD/issues/9 is implemented, add choice to the user which configuration file they want. First choice is one using configuration file with public IP, and that enpoint is alerayt implemendet in Wireguard API. Other choice is for users wishing to connect to DAppNode using Wireguard and have NAT loopback issues and configuration for that should be feched by this to-be-implemented endpoint.

**Comment by pablomendezroyo** [comment]
What do you think about serving both files at the same time and adding some explanation somehow? it may simplify things

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DAppNode_Installer/pull/150
