### ISSUE TITLE
https://installer.dappnode.io does not contain functional (or up to date) dappnode_install.sh script content

### ISSUE THREAD

**Issue by craSH** [dappnode/DAppNode_Installer#152]
The installer script referenced in the documentation (https://docs.dappnode.io/install/#install-dappnode-from-a-script) currently appears to fail to properly resolve the component versions it attempts to download, resulting in empty version variables being passed to the `wget` commands within it, ultimately resulting in 0 byte files being saved to disk which cause the remainder of the installer script to fail.

Installation script source: https://installer.dappnode.io - this redirects to `https://github.com/dappnode/DAppNode/releases/download/v0.2.44/dappnode_install.sh`, which is older than the current master version in the repository

**To Reproduce**

1. Attempt to perform script-based installation steps as documented on either a new Debian 10 or Ubuntu 20.04 system.
2. `sudo wget -O - https://installer.dappnode.io | sudo UPDATE=true bash`
3. Note that packages fail to download, and installation fails.
4. Re-running the installation command with bash in trace mode (`sudo wget -O - https://installer.dappnode.io | sudo UPDATE=true bash -x`) gives some more concrete insight in to the failure, showing this command being ran:
```++ wget -q --show-progress --progress=bar:force -O /usr/src/dappnode/DNCORE/bind.dnp.dappnode.eth__linux-amd64.txz https://github.com/dappnode/DNP_BIND/releases/download/v/bind.dnp.dappnode.eth__linux-amd64.txz```
5. Note that there is no version between the two `_` characters in the URL, as there should be.

**Expected behavior**

Script executes properly, downloading and installing components as expected.
This behavior is currently achievable by manually executing the current version of the installer script, here: https://github.com/dappnode/DAppNode_Installer/blob/63e1abb037d23634d66fceae572d30ee94145d13/scripts/dappnode_install.sh

e.g. `sudo wget -O - https://github.com/dappnode/DAppNode_Installer/blob/63e1abb037d23634d66fceae572d30ee94145d13/scripts/dappnode_install.sh | sudo UPDATE=true bash`

**Screenshots**

**DAppNode version:** n/a - attempting to install latest/current version.

**Additional context**

Seems that the master/head version of the script addresses the issues and just needs to be promoted to the current release. I wasn't really able to debug the script to determine how the version numbers get injected there to find the root cause of the failure.

**Comment by dapplion** [comment]
@craSH Thank you so much for reporting! We've fixed the existing scripts in the release so you should be able to install without issues now.

**Comment by pablomendezroyo** [comment]
should be closed by https://github.com/dappnode/DAppNode_Installer/pull/155
