### ISSUE TITLE
Fix lint issues

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode_Installer#153]
**Request**

There are not a lot of lint issues currently and should be doable to clean them all. Some suggestions are quite good indeed

https://github.com/dappnode/DAppNode_Installer/pull/149/checks?check_run_id=2682824034

**Comment by pablomendezroyo** [comment]
yeah sounds good, will focus on this once finish testing new release

**Comment by pablomendezroyo** [comment]
fixed
