### ISSUE TITLE
Generate release when downloading assets from github may fail

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode_Installer#163]
When executing `docker-compose up` the ISO generation may fail, when this situation happens the process should stop with an error

Also there should be a check at the end of the ISO generation checking for all the files:
- Image: txz
- Compose yml
- Manifest: json

**Comment by dapplion** [comment]
The script should exit with code != 0 when critical actions fail, like downloading required assets

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DAppNode_Installer/pull/166
