### ISSUE TITLE
Detect if port 80 is taken, if not install HTTPS

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode_Installer#165]
**Describe the bug**
 
Now we don't install HTTPS for script installations. If we test that the port 80 is not taken we can install HTTPS to make all DAppNodes more uniform.

Also we can make the step of docker-compose up-ing the HTTPS package safe to fail and not mandatory.

**Comment by pablomendezroyo** [comment]
Detect if port  80 in use with:
```
lsof -i -P -n |grep ":80 (LISTEN)"
```

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DAppNode_Installer/pull/167
