### ISSUE TITLE
When running restore, the command to log credentials is duplicated

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode_Installer#46]
After restoring a few time the `.dappnode_profile` tail contains the same instruction multiple times. Then, on login the console is spammed with multiple QRs. It is not a critical issue but if it has an easy solution it would polish the restore process

```
docker exec DAppNodeCore-vpn.dnp.dappnode.eth getAdminCredentials
echo -e "\n\e[32mOnce connected through the VPN (L2TP/IPSec) you can access to the administration console by following this link:\e[0m"
echo -e "\nhttp://my.admin.dnp.dappnode.eth/\n"

docker exec DAppNodeCore-vpn.dnp.dappnode.eth getAdminCredentials
echo -e "\n\e[32mOnce connected through the VPN (L2TP/IPSec) you can access to the administration console by following this link:\e[0m"
echo -e "\nhttp://my.admin.dnp.dappnode.eth/\n"

docker exec DAppNodeCore-vpn.dnp.dappnode.eth getAdminCredentials
echo -e "\n\e[32mOnce connected through the VPN (L2TP/IPSec) you can access to the administration console by following this link:\e[0m"
echo -e "\nhttp://my.admin.dnp.dappnode.eth/\n"
return
```

**Comment by vdo** [comment]
This should be fixed in 0.2.0 :
https://github.com/dappnode/DAppNode_Installer/blob/79c2dbbc974c2f5e0d683d2f70f00a714b0ae173/build/dappnode/scripts/dappnode_install.sh#L166

**Comment by dapplion** [comment]
@Shelpin Can you test this to check if it's already fixed?

**Comment by Shelpin** [comment]
In the last installation, for restoring with the dev releases of admin and dappmanager, my dappnnode was still bombed
