### ISSUE TITLE
docker-compose-admin.yml not found 

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DAppNode_Installer#57]
Hi , 

I am trying to install a fixed admin package to solve the issue of fields changing its order when trying to write new envars, I tried with this command 

```sudo wget -O - https://installer.dappnode.io | sudo ADMIN_VERSION=dev:275_envs_crazyness UPDATE=true bash```

And this has been the output

![image](https://user-images.githubusercontent.com/21328788/57929101-b3595a00-78b2-11e9-962a-155cf20d377d.png)

**Comment by dapplion** [comment]
@vdo could you diagnose if this issue is caused by the specificity of @Shelpin 's situation or an actual bug?

**Comment by vdo** [comment]
This is most probably due an environment issue on @Shelpin side, not a bug. Reopen if it happens again
