### ISSUE TITLE
Alias dappnnodde_get dappnode_admin not working installing with script

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DAppNode_Installer#58]
Hi! When you install your DAppNode via script, the alias to get the credentials does not work 

![image](https://user-images.githubusercontent.com/21328788/58161300-4d891b80-7c80-11e9-9591-67947da28463.png)

**Comment by vdo** [comment]
maybe you didn't source the profile first? or you changed from a sudoer user to root?

**Comment by Shelpin** [comment]
It was like this.... i made a clean installation via script (with update=true , that is  true as i copied EDu command in Riot) and let it installing while i was moving... when I tried to retrieve the credentials to connect (everything has been done with root user) using the alias i got the error "command not found" I used the complete docker exec -ti ..... command and it worked.

**Comment by vdo** [comment]
@Shelpin  this alias is added to the normal (sudoer) user, so if you run this as root it is not added to the profile of the root user itself.

What we could do to solve this is an automatic load of the profile in the end of the installation.
